---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - curl
    # depends
    - debhelper
    - gem2deb
    - debhelper
    - pkg-config
    - rake
    # end of depends
    - qemu
    - libvirt-bin
    - ebtables
    - dnsmasq
    - libxslt-dev
    - libxml2-dev
    - libvirt-dev
    - zlib1g-dev
    - ruby
    - ruby-dev

install:
  - rvm use system
  - wget https://releases.hashicorp.com/vagrant/1.9.7/vagrant_1.9.7_x86_64.deb
  - sudo dpkg -i vagrant_1.9.7_x86_64.deb
  - sudo apt-get install -f
  # install vagrant-libvirt
  - vagrant plugin install vagrant-libvirt
  - sudo chmod 777 /var/run/libvirt/libvirt-sock

  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - mkdir -p extra_roles
  - printf '[defaults]\nroles_path=../:extra_roles' >ansible.cfg

script:
  - vagrant plugin install vagrant-libvirt
  # See if the repo is private
  - if curl --silent --output /dev/null --dump-header - "https://github.com/${TRAVIS_REPO_SLUG}" | grep "Status:[[:space:]]*404"; then touch .private_repo; fi

  # use recent ruby, instead of default ruby 1.9
  - rvm install ruby-2.1.10
  - rvm use 2.1.10

  # Download depended roles
  - if [ -f requirements.yml ]; then ansible-galaxy install -r requirements.yml -p extra_roles; fi

  # Basic role syntax check
  #
  # If it is a private repo, it _usually_ has secret information, or encrypted
  # file. As the information security policy does not allow decryption key to
  # be transfered to third-party, encrypted files cannot be decrypted in travis
  # CI environment. Skip syntax check when it is a private repo.
  #
  - "if [ ! -f .private_repo ]; then ansible-playbook tests/travisci/tests.yml -i tests/travisci/inventory --syntax-check; fi"

  # download the QA scripts
  - git clone https://github.com/trombik/qansible.git

  # checkout the latest release
  - ( cd qansible && git checkout $(git describe --tags $(git rev-list --tags --max-count=1)) )

  # install it
  - ( cd qansible && bundle install --path vendor/bundle --with "test" && bundle exec rake build && gem install pkg/*.gem )
  - rm -rf qansible

  # git complains if user and email are not set
  - git config --global user.name "Your Name"
  - git config --global user.email "you@example.com"

  # surpress a warning from `qansible qa
  - touch .kitchen.local.yml

  # export PATH
  - export PATH="${PATH}:`rvm gemdir`/bin"

  # bundle up because rubocop is installed via Gemfile
  - bundle install --path vendor/bundle

  # run rubocop
  - bundle exec rubocop

  # run kitchen
  - env VAGRANT_LOG=debug bundle exec kitchen test

  # run the QA test
  - qansible qa

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
