---

- name: Install mosquitto
  community.general.pkgng:
    name: "{{ mosquitto_package }}"
    state: present

- name: Install or uninstall mosquitto_extra_packages
  community.general.pkgng:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ mosquitto_extra_packages }}"
