---

- name: Install mosquitto
  ansible.builtin.apt:
    name: "{{ mosquitto_package }}"
    state: present
  when:
    - mosquitto_server

- name: Install mosquitto-clients
  ansible.builtin.apt:
    name: mosquitto-clients
    state: present

- name: Install or uninstall mosquitto_extra_packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ mosquitto_extra_packages }}"
