---
# tasks file for ansible-role-mosquitto

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- include: "configure-server-{{ ansible_os_family }}.yml"
  when:
    - mosquitto_server

- include: "server.yml"
  when:
    - mosquitto_server

- include: "client.yml"
  when:
    - not mosquitto_server
