---
# tasks file for ansible-role-mosquitto

- include_vars: "{{ ansible_os_family }}.yml"

- name: "Include {{ ansible_distribution }}.yml (Debian family only)"
  include_vars: "{{ ansible_distribution }}.yml"
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution != 'Debian'

- include: "install-{{ ansible_os_family }}.yml"

- name: Create mosquitto_extra_groups
  group:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ mosquitto_extra_groups }}"

- name: Add mosquitto_user to mosquitto_extra_groups
  user:
    name: "{{ mosquitto_user }}"
    append: yes
    groups: "{{ item.name }}"
  with_items: "{{ mosquitto_extra_groups }}"
  notify:
    - Restart mosquitto

- include: "configure-server-{{ ansible_os_family }}.yml"
  when:
    - mosquitto_server

- include: "server.yml"
  when:
    - mosquitto_server

- include: "client.yml"
  when:
    - not mosquitto_server
